# Generated by Django 3.2 on 2021-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageupdate',
            name='token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
